# Use vi keys for moving around in copy mode
set-window-option -g mode-keys vi

# Bind 'v' to begin selection (like visual mode in Vim)
bind-key -T copy-mode-vi 'v' send -X begin-selection

# Bind 'y' to copy to the tmux buffer only
bind-key -T copy-mode-vi 'y' send -X copy-selection-and-cancel


set -g mouse on

#r to reload
bind r source-file ~/.tmux.conf \; display "Reloaded!"
